### ISSUE TITLE
name 'extract_detail_section' is not defined

### ISSUE THREAD

**Issue by Zeplish** [in-rolls/parse_unsearchable_rolls#1]
<img width="1375" alt="Screenshot 2021-09-11 at 8 52 08 AM" src="https://user-images.githubusercontent.com/87347147/132934645-8acd6373-8415-4302-92c1-1c063e277631.png">

**Comment by soodoku** [comment]
try https://github.com/in-rolls/parse_unsearchable_rolls/blob/master/scripts/madhya_pradesh/mp_mpi.py

**Comment by sameerhawa** [comment]
[
![image](https://user-images.githubusercontent.com/99585294/154413269-53f8f93f-9b84-4d64-a687-e861e0d1a8af.png)
](url)
