### ISSUE TITLE
[WinError 32] The process cannot access the file because it is being used by another process:

### ISSUE THREAD

**Issue by sameerhawa** [in-rolls/parse_unsearchable_rolls#2]
![image](https://user-images.githubusercontent.com/99585294/154424308-888a9387-8685-49d5-84a0-5183ac46b412.png)

**Comment by hari6000** [comment]
![Screenshot (41)](https://user-images.githubusercontent.com/14872971/185363579-c0ed8ad4-7c7f-47b8-89d8-e8fc8cd1e215.png)
